"""Init migration

Revision ID: 6e8d8dd6965f
Revises: 992ac4b3f195
Create Date: 2023-05-11 22:20:00.952127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8d8dd6965f'
down_revision = '992ac4b3f195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
